spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/myproject1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root         # ← MySQL 사용자명
    password: 1234         # ← MySQL 비밀번호

  jpa:
    hibernate:
      ddl-auto: update     # create / update / validate / none 중 선택 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false           # HTML 변경 즉시 반영 (개발용)

server:
  port: 8899

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
